apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

namePrefix: dev-

replicas:
- name: choimory-front
  count: 1
- name: choimory-api
  count: 1

images:
- name: choimory/front
  newTag: dev-latest
- name: choimory/api
  newTag: dev-latest

patchesStrategicMerge:
- replica-patch.yaml

patches:
- target:
    kind: Deployment
    name: choimory-front
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: "development"