apiVersion: apps/v1
kind: Deployment
metadata:
  name: choimory-front
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: choimory-front
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: choimory-api
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: choimory-api
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"