apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

namePrefix: prod-

replicas:
- name: choimory-front
  count: 2
- name: choimory-api
  count: 2

images:
- name: choimory/front
  newTag: v1.0.0
- name: choimory/api
  newTag: v1.0.0

patchesStrategicMerge:
- replica-patch.yaml

patches:
- target:
    kind: Ingress
    name: choimory-ingress
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts
      value: 
        - choimory.dev
        - api.choimory.dev
    - op: replace
      path: /spec/rules/0/host
      value: choimory.dev
    - op: replace
      path: /spec/rules/1/host
      value: api.choimory.dev