apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- postgres.yaml
- redis.yaml
- monitoring.yaml

commonLabels:
  project: choimory-dev
  
images:
- name: choimory/front
  newTag: latest
- name: choimory/api
  newTag: latest